pipeline {
  agent any

  stages{
    stage("build"){
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    stage("test"){
      steps{
        echo 'Running Unit Tests on worker app'
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }
    stage("package"){
      steps{
        echo 'Packaging worker app'
        dir('worker'){
          sh 'mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }
  }

  post{
    always{
      echo 'The job is complete.'
    }
  }
}
